package entidades;

public enum TipoComando {
	// INICIO SESION
	CREAR_USUARIO, INICIAR_SESION,
	
	// INTERACCION USUARIOS
	RECIBIR_MENSAJE, ENVIAR_MENSAJE_CHAT, INVITAR_USUARIO,

	// GESTIONAR SALAS
	CREAR_SALA, UNIRSE_SALA, SALIR_SALA,

	// INTERACCION SALAS
	ENVIAR_MENSAJE_SALA, OBTENER_HISTORIAL, INVITAR_A_SALA,

	// OTROS
	GENERAR_INFORME, ELIMINAR_USUARIO, LISTAR_USUARIOS, FIN
}
